# (c) Import the data in skeptic.csv and fit a SLR model. The variable names in skeptic.csv follow the same convention as those returned by  sim_slr(). Extract the fitted coefficient for β1.
# 
# (d) Re-plot the histogram from (b). Now add a vertical red line at the value of β1^ in part (c). To do so, you’ll need to use  abline(v = c, col = "red") where c is your value.
# 
# (e) Your value of β1^ in (c) should be negative. What proportion of the beta_hat_1 values is smaller than your β1^? Return this proportion, as well as this proportion multiplied by 2.
# 
# (f) Based on your histogram and part (e), do you think the skeptic.csv data could have been generated by the model given above? Briefly explain.



birthday = 19920720
set.seed(birthday)

num_obs = 75
beta_0  = 3
beta_1  = 0
sigma   = 2
x = runif(n = 75, 0, 10)



sim_slr = function(x, beta_0 = 3, beta_1 = 0, sigma = 2) {
  n = length(x)
  epsilon = rnorm(n, mean = 0, sd = sigma)
  y = beta_0 + beta_1 * x + epsilon
  data.frame(predictor = x, response = y)
}

options(scipen = 999)
beta_hat_1 <- as.vector(rep(0,2500))
for (i in 1:2500)
{
  sim_temp <- sim_slr(x = x, beta_0 = 3, beta_1 = 0, sigma = 2)
  slr_temp <-  lm(response ~ predictor,data = sim_temp)
  coef <-  coef(slr_temp)[2]
  beta_hat_1[i] <- coef
  i <- i+1
}


histogram_beta_hat1 = hist(beta_hat_1, breaks = 50,
                           main = "Histogram of Beta Hat1",
                           xlab = " Beta Hat1")
























skeptic <- read.csv("skeptic.csv")

slr_skeptic <- lm(response~predictor, data =skeptic)
beta_1hat <- summary(slr_skeptic)$coefficients[1,1]





